FROM busybox:latest
COPY *.sh /usr/local/bin/

ENV CONFIG_PATH=/config
ENV MAPS_DIR=/maps

ENV GENERATE_EC=1
ENV GENERATE_SV=1
ENV GENERATE_TW=1
ENV GENERATE_PERMISSIONS=1
ENV GENERATE_EXECS=1

ENV GENERATE_VG=1
ENV GENERATE_VG_ADS=1
ENV GENERATE_VG_MISC=1
ENV GENERATE_VG_SCORELIMITS=1
ENV GENERATE_VG_SPECTATOR_SLOTS=1
ENV GENERATE_VG_MAPS=1

ENV REGENERATE_VG=1

ENTRYPOINT ["init.sh"]
